directories:
  output: release/${version}
  buildResources: build
appId: com.lysis.app
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
mac:
  artifactName: ${productName}_${version}.${ext}
  target:
    - dmg
win:
  target:
    - target: nsis
      arch:
        - x64
  artifactName: ${productName}_${version}.${ext}
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
electronVersion: 30.5.1
